export enum IpcEvents {
  CLOSE_SETTINGS = "CLOSE_SETTINGS",
  OPEN_SETTINGS = "OPEN_SETTINGS",
  SYNC_GET_APP_CONFIG = "SYNC_GET_APP_CONFIG",
  SYNC_UPDATE_PREFERENCES_JSON = "SYNC_UPDATE_PREFERENCES_JSON",
  SYNC_OPEN_SEARCH_WINDOW = "SYNC_OPEN_SEARCH_WINDOW",
  SYNC_GET_EXTENSIONS = "SYNC_GET_EXTENSIONS",
  EXTENSION_CONNECTED = "EXTENSION_CONNECTED",
  SYNC_REMOVE_EXTENSION = "SYNC_REMOVE_EXTENSION",
  SYNC_GET_PRODUCT_TOUR = "SYNC_GET_PRODUCT_TOUR",
  SYNC_RESET_PRODUCT_TOUR = "SYNC_RESET_PRODUCT_TOUR",
  SYNC_FINISH_PRODUCT_TOUR = "SYNC_FINISH_PRODUCT_TOUR",
  SYNC_PRODUCT_TOUR_UPDATED = "SYNC_PRODUCT_TOUR_UPDATED",
}

// message send to main
export const ipcMainEvents = [
  IpcEvents.OPEN_SETTINGS,
  IpcEvents.CLOSE_SETTINGS,
  IpcEvents.SYNC_GET_APP_CONFIG,
  IpcEvents.SYNC_UPDATE_PREFERENCES_JSON,
  IpcEvents.SYNC_OPEN_SEARCH_WINDOW,
  IpcEvents.SYNC_GET_EXTENSIONS,
  IpcEvents.SYNC_REMOVE_EXTENSION,
  IpcEvents.SYNC_GET_PRODUCT_TOUR,
  IpcEvents.SYNC_FINISH_PRODUCT_TOUR,
  IpcEvents.SYNC_RESET_PRODUCT_TOUR,
];

// message send to renderer
export const ipcRendererEvents = [
  IpcEvents.OPEN_SETTINGS,
  IpcEvents.CLOSE_SETTINGS,
  IpcEvents.SYNC_GET_APP_CONFIG,
  IpcEvents.SYNC_UPDATE_PREFERENCES_JSON,
  IpcEvents.EXTENSION_CONNECTED,
  IpcEvents.SYNC_PRODUCT_TOUR_UPDATED,
];

export const WEBCONTENTS_READY_FOR_IPC_SIGNAL =
  "WEBCONTENTS_READY_FOR_IPC_SIGNAL";

export type EventResponse = {
  status: boolean;
  payload?: any;
  error?: unknown;
};

export type EventRequest = {
  subject: string;
  payload?: unknown;
};
