// why not enum? object support partial import
import { CHECK_SERVICE_HEALTH_INTERVAL_VALUE } from "@bitsky/shared"

const SERVICE_DISCOVER_CONSTANTS = {
  CHECK_SERVICE_HEALTH_INTERVAL_VALUE: CHECK_SERVICE_HEALTH_INTERVAL_VALUE
}

export default SERVICE_DISCOVER_CONSTANTS
